# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title  compute strand information of sliding window based on coverage
#'
#' @description non
#'
#' @param covPosLen the length the Rle object, which is the coverage comes from positive reads
#' @param covPosVal the value the Rle object, which is the coverage comes from positive reads
#' @param covNegLen the length the Rle object, which is the coverage comes from negative reads
#' @param covNegVal the value the Rle object, which is the coverage comes from negative reads
#' @param end the last base on the reference chromosome that the sliding window atteint
#' @param readLength the average length of reads
#' @param win the size of the sliding window
#' @param step the step of the sliding window
#' @param minCov if a window has the max coverage least than minCov, then it will be rejected
#' @param maxCov if a window has the max coverage greater than maxCov, then it will be kept
#' @param logitThreshold the logit of the threshold
#'
#' @return A list of two data frames Plus and Minus which respectively contains information of positive windows and negative windows: 'win' is the window number, and 'value' is the normalized estimated value to be tested
#' 
#' @examples
#' computeWin(c(10000,200,30,1,20,50),c(0,2,3,4,1,2),c(10020,300,20,1,10,15),c(0,1,3,5,1,3),100,10200,1000,100,0,0,0.8472979)
#' 
#' @export
#' 
computeWin <- function(covPosLen, covPosVal, covNegLen, covNegVal, readLength, end, win, step, minCov, maxCov, logitThreshold) {
    .Call('rnaCleanR_computeWin', PACKAGE = 'rnaCleanR', covPosLen, covPosVal, covNegLen, covNegVal, readLength, end, win, step, minCov, maxCov, logitThreshold)
}

#' @title  compute strand information of sliding window based on coverage
#'
#' @description non
#'
#' @param covPosLen the length the Rle object, which is the coverage comes from positive reads
#' @param covPosVal the value the Rle object, which is the coverage comes from positive reads
#' @param covNegLen the length the Rle object, which is the coverage comes from negative reads
#' @param covNegVal the value the Rle object, which is the coverage comes from negative reads
#' @param readLength the average length of reads
#' @param end the last base on the reference chromosome that the sliding window atteint
#' @param win the size of the sliding window
#' @param step the step of the sliding window
#' @param minCov if a window has the max coverage least than minCov, then it will be rejected
#' @param maxCov if a window has the max coverage greater than maxCov, then it will be kept
#' @param logitThreshold the logit of the threshold
#'
#' @return A list of two data frames Plus and Minus which respectively contains information of positive windows and negative windows: 'win' is the window number, and 'value' is the normalized estimated value to be tested
#' 
#' @examples
#' computeWin1(c(10000,200,30,1,20,50),c(0,2,3,4,1,2),c(10020,300,20,1,10,15),c(0,1,3,5,1,3),100,10200,1000,100,0,0,0.8472979)
#' 
#' @export
computeWin1 <- function(covPosLen, covPosVal, covNegLen, covNegVal, readLength, end, win, step, minCov, maxCov, logitThreshold) {
    .Call('rnaCleanR_computeWin1', PACKAGE = 'rnaCleanR', covPosLen, covPosVal, covNegLen, covNegVal, readLength, end, win, step, minCov, maxCov, logitThreshold)
}

#' @title  compute strand information of sliding window based on coverage
#'
#' @description non
#'
#' @param covPosLen the length the Rle object, which is the coverage comes from positive reads
#' @param covPosVal the value the Rle object, which is the coverage comes from positive reads
#' @param covNegLen the length the Rle object, which is the coverage comes from negative reads
#' @param covNegVal the value the Rle object, which is the coverage comes from negative reads
#' @param readLength the average length of reads
#' @param end the last base on the reference chromosome that the sliding window atteint
#' @param win the size of the sliding window
#' @param step the step of the sliding window
#' @param minCov if a window has the max coverage least than minCov, then it will be rejected
#' @param maxCov if a window has the max coverage greater than maxCov, then it will be kept
#' @param logitThreshold the logit of the threshold
#'
#' @return A list of two data frames Plus and Minus which respectively contains information of positive windows and negative windows: 'win' is the window number, and 'value' is the normalized estimated value to be tested
#' 
#' @examples
#' computeWin2(c(10000,200,30,1,20,50),c(0,2,3,4,1,2),c(10020,300,20,1,10,15),c(0,1,3,5,1,3),100,10200,1000,100,0)
#' 
#' @export
computeWin2 <- function(covPosLen, covPosVal, covNegLen, covNegVal, readLength, end, win, step, minCov) {
    .Call('rnaCleanR_computeWin2', PACKAGE = 'rnaCleanR', covPosLen, covPosVal, covNegLen, covNegVal, readLength, end, win, step, minCov)
}

getIndex <- function(strand) {
    .Call('rnaCleanR_getIndex', PACKAGE = 'rnaCleanR', strand)
}

keepRead <- function(startPosAl, endPosAl, groupPos, startNegAl, endNegAl, groupNeg, proporWinPos, proporWinNeg, keepWinPos, keepWinNeg, maxWin, win, step, errorRate) {
    .Call('rnaCleanR_keepRead', PACKAGE = 'rnaCleanR', startPosAl, endPosAl, groupPos, startNegAl, endNegAl, groupNeg, proporWinPos, proporWinNeg, keepWinPos, keepWinNeg, maxWin, win, step, errorRate)
}

